### ISSUE TITLE
Issue with 'fight_target_player' method in code

### ISSUE THREAD

**Issue by a01508252** [TBIAPBC/APBC2023#50]
I have encountered an error when running @KilianG98's script (KilianG98-RobotRace.py). Just wanted to check if you are aware of it :-) 

The error message I received is as follows:

```
ERROR: player 3 raised an exception: 'NoneType' object has no attribute 'Status'
Traceback (most recent call last):
  File "/Users/Yannick/Documents/GitHub/APBC2023/A6/simulator.py", line 317, in _handle_fighting
    fight_target = player.fight_target_player(self._pubStat[pId])  # ask them if they want to fight a player
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Yannick/Documents/GitHub/APBC2023/A6/KilianG98-RobotRace.py", line 72, in fight_target_player
    print(other.Status.x)
          ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'Status'
``

**Comment by KilianG98** [comment]
oh, thank you for pointing that out! It was not meant to be in there.
